import { PlayerRoleEnum } from "@features/team/enums";
import { PlayerModel } from "@features/team/models";

export const PLAYERS_LIST: PlayerModel[] = [
  {
    id: "player-001",
    name: "Casey Morgan",
    type: PlayerRoleEnum.Batting,
    battingSkill: 82,
    bowlingSkill: 22,
    fieldingSkill: 74,
  },
  {
    id: "player-002",
    name: "Morgan Riley",
    type: PlayerRoleEnum.Batting,
    battingSkill: 78,
    bowlingSkill: 20,
    fieldingSkill: 70,
  },
  {
    id: "player-003",
    name: "Riley Quinn",
    type: PlayerRoleEnum.Batting,
    battingSkill: 76,
    bowlingSkill: 18,
    fieldingSkill: 72,
  },
  {
    id: "player-004",
    name: "Quinn Avery",
    type: PlayerRoleEnum.Batting,
    battingSkill: 79,
    bowlingSkill: 25,
    fieldingSkill: 73,
  },
  {
    id: "player-005",
    name: "Avery Peyton",
    type: PlayerRoleEnum.WicketKeeper,
    battingSkill: 65,
    bowlingSkill: 10,
    fieldingSkill: 85,
  },
  {
    id: "player-006",
    name: "Peyton Skyler",
    type: PlayerRoleEnum.WicketKeeper,
    battingSkill: 62,
    bowlingSkill: 12,
    fieldingSkill: 84,
  },
  {
    id: "player-007",
    name: "Skyler Dakota",
    type: PlayerRoleEnum.WicketKeeper,
    battingSkill: 60,
    bowlingSkill: 10,
    fieldingSkill: 83,
  },
  {
    id: "player-008",
    name: "Dakota Reese",
    type: PlayerRoleEnum.AllRounder,
    battingSkill: 70,
    bowlingSkill: 68,
    fieldingSkill: 78,
  },
  {
    id: "player-009",
    name: "Alex Morgan",
    type: PlayerRoleEnum.Batting,
    battingSkill: 85,
    bowlingSkill: 18,
    fieldingSkill: 75,
  },
  {
    id: "player-010",
    name: "Sam Taylor",
    type: PlayerRoleEnum.Batting,
    battingSkill: 83,
    bowlingSkill: 22,
    fieldingSkill: 76,
  },
  {
    id: "player-011",
    name: "Taylor Jordan",
    type: PlayerRoleEnum.Batting,
    battingSkill: 80,
    bowlingSkill: 20,
    fieldingSkill: 74,
  },
  {
    id: "player-012",
    name: "Jordan Casey",
    type: PlayerRoleEnum.Batting,
    battingSkill: 81,
    bowlingSkill: 23,
    fieldingSkill: 77,
  },
  {
    id: "player-013",
    name: "Emily Brooks",
    type: PlayerRoleEnum.AllRounder,
    battingSkill: 73,
    bowlingSkill: 68,
    fieldingSkill: 79,
  },
  {
    id: "player-014",
    name: "Liam Carter",
    type: PlayerRoleEnum.AllRounder,
    battingSkill: 76,
    bowlingSkill: 18,
    fieldingSkill: 70,
  },
  {
    id: "player-015",
    name: "Isabella Nguyen",
    type: PlayerRoleEnum.Bowling,
    battingSkill: 22,
    bowlingSkill: 82,
    fieldingSkill: 64,
  },
  {
    id: "player-016",
    name: "Chloe Martínez",
    type: PlayerRoleEnum.AllRounder,
    battingSkill: 69,
    bowlingSkill: 66,
    fieldingSkill: 78,
  },
  {
    id: "player-017",
    name: "Noah Thompson",
    type: PlayerRoleEnum.Bowling,
    battingSkill: 33,
    bowlingSkill: 87,
    fieldingSkill: 62,
  },
  {
    id: "player-018",
    name: "Ava Dubois",
    type: PlayerRoleEnum.AllRounder,
    battingSkill: 58,
    bowlingSkill: 12,
    fieldingSkill: 83,
  },
  {
    id: "player-019",
    name: "Ethan Singh",
    type: PlayerRoleEnum.Batting,
    battingSkill: 81,
    bowlingSkill: 24,
    fieldingSkill: 73,
  },
  {
    id: "player-020",
    name: "Lily Chen",
    type: PlayerRoleEnum.AllRounder,
    battingSkill: 72,
    bowlingSkill: 69,
    fieldingSkill: 76,
  },
];
